//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivery_Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adTable
    {
        public int ID { get; set; }
        public string Tags { get; set; }
        public string PhotoLinks { get; set; }
        public string ProductLinks { get; set; }
        public string extraColumn { get; set; }
    }
}
