//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExternalProgram.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public string OrderNumber { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Channel { get; set; }
        public string toId { get; set; }
        public string toName { get; set; }
        public string FrmID { get; set; }
        public string FrmName { get; set; }
        public string svcURL { get; set; }
        public string conID { get; set; }
        public int ID { get; set; }
    }
}
